### ISSUE TITLE
需要更新

### ISSUE THREAD

**Issue by hanfei831** [gottyduke/MHW-I_CNTextColor#2]
经过排查确定，更新前置后，使用此mod时可正常进入游戏标题界面，选择角色后，加载过程中闪退，问题可复现。
以及，贴吧也能找到他人有同样问题：https://tieba.baidu.com/p/8657402112。
不知道能否得到维护？

**Comment by gottyduke** [comment]
游戏更新了吗？！如果是的话那我更新下插件
